# Generated by Django 5.0.6 on 2024-06-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_employees_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
