# Generated by Django 5.0.6 on 2024-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_employees_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=40, null=True),
        ),
    ]
