# Generated by Django 5.0.6 on 2024-06-22 14:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_employees_universty'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='mobile1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='mobile2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
