# Generated by Django 5.0.6 on 2024-06-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_employees_mobile1_employees_mobile2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='universty',
            field=models.CharField(choices=[('Cairo Universty', 'Cairo Universty'), ('Alexandria Universty', 'Alexandria Universty')], max_length=40, null=True),
        ),
    ]
