# Generated by Django 5.0.6 on 2024-06-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_employees_universty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=51),
        ),
    ]
