# Generated by Django 5.0.6 on 2024-06-23 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_tasks_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='willdate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='will complete it in'),
        ),
    ]
