# Generated by Django 5.0.6 on 2024-06-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_tasks_willdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='willdate',
            field=models.DateTimeField(verbose_name='will complete it in'),
        ),
    ]
