# Generated by Django 5.0.6 on 2024-06-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_tasks_willdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
