# Generated by Django 5.0.6 on 2024-06-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_tasks_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='photos/logo')),
                ('company_name', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
