# Generated by Django 5.0.6 on 2024-06-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_companydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
