# Generated by Django 5.0.6 on 2024-06-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_companydata_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='logo',
            field=models.ImageField(null=True, upload_to='photos/logo'),
        ),
    ]
