# Generated by Django 5.0.6 on 2024-06-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_companydata_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/logo'),
        ),
    ]
