# Generated by Django 5.0.6 on 2024-06-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_companydata_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='logo',
            field=models.ImageField(null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
