# Generated by Django 5.0.6 on 2024-06-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_companydata_address_companydata_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='manager_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
