# Generated by Django 5.0.6 on 2024-06-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_companydata_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
