# Generated by Django 5.0.6 on 2024-06-26 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_employees_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='universty',
        ),
        migrations.AddField(
            model_name='employees',
            name='job',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 7, 3), null=True),
        ),
    ]
