# Generated by Django 5.0.6 on 2024-06-26 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_remove_employees_sex_remove_employees_universty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='job',
            field=models.CharField(choices=[('software_engineer', 'Software Engineer'), ('data_analyst', 'Data Analyst'), ('project_manager', 'Project Manager'), ('hr_specialist', 'HR Specialist'), ('data_scientist', 'Data Scientist'), ('ux_designer', 'UX Designer'), ('marketing_director', 'Marketing Director'), ('sales_director', 'Sales Director')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 7, 26), null=True),
        ),
    ]
