# Generated by Django 5.0.6 on 2024-06-26 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_employees_job_alter_employees_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='work_schedule',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)]),
        ),
    ]
