# Generated by Django 5.0.6 on 2024-06-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_employees_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='cv',
            field=models.ImageField(blank=True, null=True, upload_to='photos/cvs'),
        ),
    ]
