# Generated by Django 3.2.12 on 2024-07-10 19:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_alter_employees_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='employment_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 8, 9), null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='work_schedule',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)], verbose_name='Work Schedule(hours)'),
        ),
    ]
