# Generated by Django 3.2.12 on 2024-07-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20240710_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='accept',
            field=models.BooleanField(null=True),
        ),
    ]
