# Generated by Django 3.2.12 on 2024-07-18 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_auto_20240717_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earn', models.IntegerField(null=True)),
                ('water', models.IntegerField(null=True)),
                ('gas', models.IntegerField(null=True)),
                ('transport', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 8, 17), null=True),
        ),
    ]
