# Generated by Django 3.2.12 on 2024-07-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_auto_20240718_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.CharField(choices=[('admin', 'admin'), ('test', 'test'), ('tra', 'tra')], max_length=40),
        ),
    ]
