# Generated by Django 3.2.12 on 2024-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_alter_tasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('test', 'test'), ('tra', 'tra')], max_length=40, null=True),
        ),
    ]
